version: 2

sources:
  - name: raw_customers
    description: "Raw customer data from the e-commerce platform"
    tables:
      - name: customers
        description: "Table containing customer information"


  - name: raw_payments
    description: "Raw payment data from the e-commerce platform"
    tables:
      - name: payments
        description: "Table containing payment transaction details"
  - name: raw
    database: jaffle-shop-461615
    schema: my_ecom_demo
    tables:
      - name: events
        identifier: events
      - name: orders
        identifier: orders
models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: revenue
        tests:
          - not_null

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
